
function startVocabulary(data){'use strict';
const entries=data.entries,documents=data.documents,docs=Object.fromEntries(documents.map(d=>[d.id,d]));
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=s=>String(s??'').normalize('NFKC').toLowerCase();
const key='csit882-week9-vocabulary-v2',legacy='csit882-week9-vocabulary-v1';
const state={category:'all',week:'all',lecture:'all',query:'',recall:false,revealed:new Set(),saved:new Set(),orphans:new Set(),savedOnly:false,fontSize:18,stored:{}};
const aliasMap=new Map();for(const e of entries)for(const id of [e.id,...e.legacyIds]){if(!aliasMap.has(id))aliasMap.set(id,new Set());aliasMap.get(id).add(e.id);}
function mergeSaved(values){for(const id of values){if(typeof id!=='string')continue;const matches=aliasMap.get(id);if(matches)for(const target of matches)state.saved.add(target);else state.orphans.add(id);}}
try{const raw=JSON.parse(localStorage.getItem(key)||localStorage.getItem(legacy)||'null');if(raw){state.stored=raw;mergeSaved(Array.isArray(raw.saved)?raw.saved:[]);state.fontSize=Math.max(15,Math.min(24,Number(raw.fontSize)||18));}}catch(e){$('storage-note').hidden=false;}
function persist(){try{localStorage.setItem(key,JSON.stringify({...state.stored,saved:[...state.saved,...state.orphans],fontSize:state.fontSize}));}catch(e){$('storage-note').hidden=false;}}
function words(){return norm(state.query.trim()).split(/\s+/).filter(Boolean);}
function highlight(value){const text=String(value??''),q=words().sort((a,b)=>b.length-a.length),lower=norm(text);if(!q.length||lower.length!==text.length)return esc(text);let out='',at=0;while(at<text.length){let next=-1,word='';for(const w of q){const found=lower.indexOf(w,at);if(found>=0&&(next<0||found<next)){next=found;word=w;}}if(next<0){out+=esc(text.slice(at));break;}out+=esc(text.slice(at,next))+'<mark>'+esc(text.slice(next,next+word.length))+'</mark>';at=next+word.length;}return out;}
function refs(m){return m.references;}
function contexts(m){return m.contexts||[{week:m.week,lecture:m.lecture}];}
function meaningMatches(m){return contexts(m).some(c=>(state.week==='all'||c.week===state.week)&&(state.lecture==='all'||c.lecture===state.lecture));}
function documentWeeks(d){return d.weeks||[d.week];}
function matchingContexts(m){return contexts(m).filter(c=>(state.week==='all'||c.week===state.week)&&(state.lecture==='all'||c.lecture===state.lecture));}
function senseLabel(m){return [...new Set(matchingContexts(m).map(c=>c.week+' · '+docs[c.lecture].name))].join(' / ');}
function meanings(e){return e.meanings.filter(meaningMatches);}
function searchable(e){return norm([e.term,...e.aliases,...e.meanings.flatMap(m=>[m.zh,m.note,m.simpleEnglish,...(m.usageNotes||[]).flatMap(u=>[u.zh,u.note]),...m.references.flatMap(r=>[r.name,r.location]),...m.definitions.map(o=>o.text),...m.excerpts.map(o=>o.text)])].join(' '));}
const searchIndex=new Map(entries.map(e=>[e.id,searchable(e)]));
function selected(){const q=words();return entries.filter(e=>(state.category==='all'||e.category===state.category)&&meanings(e).length&&(!state.savedOnly||state.saved.has(e.id))&&q.every(w=>searchIndex.get(e.id).includes(w)));}
function ranges(values){const numbers=[...new Set(values)].sort((a,b)=>a-b),parts=[];for(let i=0;i<numbers.length;i++){let start=numbers[i],end=start;while(i+1<numbers.length&&numbers[i+1]===end+1)end=numbers[++i];parts.push(start===end?String(start):start+'–'+end);}return parts.join('、');}
function sourceList(references,covered=false){const groups=new Map();for(const r of references){if(!groups.has(r.document))groups.set(r.document,[]);groups.get(r.document).push(r);}return[...groups].map(([id,rr])=>{const pages=rr.filter(r=>r.page).map(r=>r.page),lines=rr.filter(r=>r.line).map(r=>r.line),extra=rr.filter(r=>!r.page&&!r.line).map(r=>covered?'位置待核实':r.location);return `<p><span class="file">${esc(docs[id].name)}</span> · ${pages.length?'PDF第'+ranges(pages)+'页（幻灯片同页码）':lines.length?'TXT第'+ranges(lines)+'行'+(rr.some(r=>r.charStart)?' · 字符'+[...new Set(rr.filter(r=>r.charStart).map(r=>r.charStart+'–'+r.charEnd))].join('、'):''):esc([...new Set(extra)].join('；'))}</p>`;}).join('');}
function original(o){return `<p class="quote-label">${esc(o.label)}</p><blockquote lang="en">${highlight(o.text)}</blockquote><div class="source-list">${sourceList(o.references)}</div>`;}
function explanation(e,mm){return mm.map((m,i)=>`<div class="sense">${mm.length>1?`<span class="sense-label">${esc(senseLabel(m))}</span>`:''}<p class="meaning">${highlight(m.zh)}</p><details class="detail"><summary>必要说明与简单英文</summary><div class="detailbody"><p class="basis">${esc(m.basis)} · 整理解释</p><p>${highlight(m.note||'按资料中的本义项整理。')}</p><p lang="en"><b>Simple English：</b>${highlight(m.simpleEnglish)}</p>${(m.usageNotes||[]).map(u=>`<p>${highlight(u.zh)} ${highlight(u.note)}${u.simpleEnglish?`<br><span lang="en">${highlight(u.simpleEnglish)}</span>`:''}</p>`).join('')}</div></details><details class="detail"><summary>${m.definitions.length?'课件原文定义与补充短句':'资料短句（当前资料未给出正式定义）'}</summary><div class="detailbody">${m.definitions.length?m.definitions.map(original).join(''):'<p>当前资料未给出正式定义。</p>'}${m.excerpts.map(original).join('')}${!m.excerpts.length&&!m.definitions.length?'<p>以上为整理解释或必要基础释义，不是课件原文定义。</p>':''}</div></details></div>`).join('');}
function article(e){const covered=state.recall&&!state.revealed.has(e.id),mm=meanings(e),saved=state.saved.has(e.id);return `<article class="entry${covered?' covered':''}" id="entry-${esc(e.id)}"><div class="term"><h3 lang="en">${state.recall?`<button class="word-button" data-toggle="${esc(e.id)}" aria-expanded="${!covered}">${highlight(e.term)}</button>`:highlight(e.term)}</h3><span class="category ${e.category}">${e.category==='technical'?'专业英语 · Technical terms':'阅读词汇 · Reading vocabulary'}</span><div class="source-list">${sourceList(mm.flatMap(refs),covered)}</div></div><div class="body">${covered?'<p class="recall-hint">先回忆，再查看解释。</p>':explanation(e,mm)}</div><div class="entryfoot">${state.recall?`<button data-toggle="${esc(e.id)}" aria-expanded="${!covered}">${covered?'查看解释':'隐藏解释'}</button>`:''}<button class="star" data-save="${esc(e.id)}" aria-pressed="${saved}" aria-label="${saved?'取消收藏':'收藏'} ${esc(e.term)}">${saved?'★':'☆'}</button></div></article>`;}
function lectureOptions(){const available=documents.filter(d=>d.kind==='pdf'&&(state.week==='all'||documentWeeks(d).includes(state.week)));if(!available.some(d=>d.id===state.lecture))state.lecture='all';$('lecture').innerHTML='<option value="all">全部课件</option>'+available.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('');$('lecture').value=state.lecture;}
function font(){document.documentElement.style.setProperty('--size',state.fontSize+'px');$('size-label').textContent=state.fontSize;$('smaller').disabled=state.fontSize<=15;$('larger').disabled=state.fontSize>=24;}
function render(){const list=selected();$('result-status').textContent=list.length?'匹配 '+list.length+' 条词汇':'没有匹配的词条';$('clear').hidden=!state.query;$('recall-note').hidden=!state.recall;$('source-notes').hidden=state.recall;$('saved-only').setAttribute('aria-pressed',String(state.savedOnly));if(!list.length){$('results').innerHTML='<div class="empty">试试更短的搜索词，或清除筛选。</div>';return;}const grouped=new Map();for(const e of list){const m=meanings(e)[0],id=state.lecture!=='all'?state.lecture:matchingContexts(m)[0].lecture;if(!grouped.has(id))grouped.set(id,[]);grouped.get(id).push(e);}const order=documents.filter(d=>d.kind==='pdf').map(d=>d.id);$('results').innerHTML=[...grouped].sort((a,b)=>order.indexOf(a[0])-order.indexOf(b[0])).map(([id,ee])=>`<section class="lecture-section"><h2 class="sectionhead">${esc(docs[id].name)}<small>${esc(state.week==='all'?documentWeeks(docs[id]).join(' / '):state.week)}</small></h2><div>${ee.map(article).join('')}</div></section>`).join('');}
function reset(){Object.assign(state,{category:'all',week:'all',lecture:'all',query:'',savedOnly:false});$('category').value='all';$('week').value='all';$('search').value='';lectureOptions();render();}
$('week').innerHTML='<option value="all">全部周次</option>'+[...new Set(documents.flatMap(documentWeeks))].map(w=>`<option value="${esc(w)}">${esc(w)}</option>`).join('');
$('source-checks').innerHTML=documents.map(d=>`<p><b>${esc(d.name)}</b> · ${esc(documentWeeks(d).join(' / '))}${d.pages?' · '+d.pages+'页':''}</p>`).join('')+Object.values(data.sourceChecks).map(s=>`<p>${esc(s)}</p>`).join('');
$('issues').innerHTML='<ul>'+data.issues.map(i=>`<li><b>${esc(i.title)}</b><p>${esc(i.source)}</p><p>${esc(i.detail)}</p></li>`).join('')+'</ul>'+data.legacySourceNotesHtml;
$('search').addEventListener('input',()=>{state.query=$('search').value;render();});$('clear').addEventListener('click',()=>{state.query='';$('search').value='';render();$('search').focus();});$('reset').addEventListener('click',reset);
for(const id of ['category','week','lecture'])$(id).addEventListener('change',()=>{state[id]=$(id).value;if(id==='week')lectureOptions();render();});
$('recall').addEventListener('change',()=>{state.recall=$('recall').checked;state.revealed.clear();render();});$('saved-only').addEventListener('click',()=>{state.savedOnly=!state.savedOnly;render();});
$('results').addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.toggle&&state.recall){const id=b.dataset.toggle;if(state.revealed.has(id))state.revealed.delete(id);else state.revealed.add(id);render();document.getElementById('entry-'+id)?.querySelector('[data-toggle]')?.focus({preventScroll:true});}else if(b.dataset.save){const id=b.dataset.save;if(state.saved.has(id))state.saved.delete(id);else state.saved.add(id);persist();render();}});
for(const [id,delta]of[['smaller',-1],['larger',1]])$(id).addEventListener('click',()=>{state.fontSize=Math.max(15,Math.min(24,state.fontSize+delta));font();persist();});
$('export-saved').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({course:'CSIT882',version:3,saved:[...state.saved,...state.orphans],fontSize:state.fontSize},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='CSIT882-favorites.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('transfer-note').textContent='已导出收藏备份。';});
$('import-saved').addEventListener('click',()=>$('import-file').click());$('import-file').addEventListener('change',async()=>{try{const f=$('import-file').files[0];if(!f)return;const raw=JSON.parse(await f.text());if(raw.course!=='CSIT882'||!Array.isArray(raw.saved))throw Error();mergeSaved(raw.saved);persist();render();$('transfer-note').textContent='已合并导入，原收藏保留。';}catch(e){$('transfer-note').textContent='无法导入；请选择CSIT882收藏备份文件。';}finally{$('import-file').value='';}});
font();lectureOptions();render();
}

(async()=>{try{const response=await fetch('./course-data.json?v=@@DATA_HASH@@');
if(!response.ok)throw Error('Vocabulary data could not be loaded');
startVocabulary(await response.json());}catch(error){const target=document.getElementById('result-status');
target.textContent='词汇暂时未能加载，请刷新页面后重试。';target.setAttribute('role','alert');}})();
